# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d77763c2bfe7cfbba8096981286f32fc49ad886ab5a00a1497b42c0f10ca9c072da5e76ba86fac12a4189d0a1a00c7ea557df67cad5aff1a6c5b176255c9e1e

test:
  secret_key_base: 09894ea036be270b529b8778c39a8c986cb40e97c7717018ec5d302ee275e3a9967668e5d31d50ef2d4378f9ad8f3ed08ed8e53151d9dc3ea7aaaba8923d0e28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
